<?php

namespace AppBundle\Repository;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends \Doctrine\ORM\EntityRepository
{
	public function findActualEvents($companyId) {
		$em = $this->getEntityManager();
		$currentTime = new \DateTime();
		$currentTime->setTime(0, 0, 0);
		$query = $em
				->createQuery('SELECT e FROM AppBundle:Event e WHERE e.company = :companyId AND e.deleted = 0 AND e.start > :currentTime ORDER BY e.start')
				->setParameter('companyId', $companyId)
				->setParameter('currentTime', $currentTime);
		return $query->getResult();
	}

	public function findPastEvents($companyId) {
		$em = $this->getEntityManager();
		$currentTime = new \DateTime();
		$currentTime->setTime(0, 0, 0);
		$query = $em
				->createQuery('SELECT e FROM AppBundle:Event e WHERE e.company = :companyId AND e.deleted = 0 AND e.start < :currentTime ORDER BY e.start')
				->setParameter('companyId', $companyId)
				->setParameter('currentTime', $currentTime);
		return $query->getResult();
	}

	public function findDeletedEvents($companyId) {
		$em = $this->getEntityManager();
		$query = $em
				->createQuery('SELECT e FROM AppBundle:Event e WHERE e.company = :companyId AND e.deleted = 1 ORDER BY e.start')
				->setParameter('companyId', $companyId);
		return $query->getResult();
	}
}
