<?php

namespace AppBundle\Repository;

/**
 * GuestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GuestRepository extends \Doctrine\ORM\EntityRepository {
	/**
	 * Search Guests in database
	 * @param int $companyId
	 * @param boolean $findHidden if true, returns hidden records too
	 * @param boolean $findDeleted if true, returns deleted records too
	 * @return array
	 * @return \AppBundle\Entity\Guest $guest
	 */
	public function findCompanyGuests($companyId, $findHidden = FALSE, $findDeleted = FALSE) {
		$hidden = ($findHidden) ? '' : ' AND g.hidden = 0';
		$deleted = ($findDeleted) ? '' : ' AND g.deleted = 0';
		$em = $this->getEntityManager();
		$query = $em
				->createQuery("SELECT g FROM AppBundle:Guest g WHERE g.guestOfCompany = :companyId$deleted$hidden ORDER BY g.created")
				->setParameter('companyId', $companyId);
		return $query->getResult();
	}
}
